// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for PlayersFunction
 */
export interface PlayersFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/players.
 */
export class PlayersFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PlayersFunctionProps) {
    super(scope, id, {
      description: 'src/players.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/players.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}